// Code generated by Remoto; DO NOT EDIT.

package stub

import (
	"context"
	"encoding/json"
	"io"
	"io/ioutil"
	"mime/multipart"
	"net/http"
	"strconv"

	"github.com/machinebox/remoto/remototypes"
	"github.com/oxtoacart/bpool"
	"github.com/pkg/errors"
)


// BankClient accesses remote Bank services.
type BankClient struct {
	// endpoint is the HTTP endpoint of the remote server.
	endpoint string
	// httpclient is the http.Client to use to make requests.
	httpclient *http.Client
	// bufs is a buffer pool
	bufs *bpool.BufferPool
}

// NewBankClient makes a new BankClient that will
// use the specified http.Client to make requests.
func NewBankClient(endpoint string, client *http.Client) *BankClient {
	return &BankClient{
		endpoint: endpoint,
		httpclient: client,
		bufs: bpool.NewBufferPool(48),
	}
}



func (c *BankClient) Balance(ctx context.Context, request *BalaceRequest) (*Response, error) {
	resp, err := c.BalanceMulti(ctx, []*BalaceRequest{request})
	if err != nil {
		return nil, err
	}
	if len(resp) == 0 {
		return nil, errors.New("BankClient.Balance: no response")
	}
	return resp[0], nil
}

func (c *BankClient) BalanceMulti(ctx context.Context, requests []*BalaceRequest) ([]*Response, error) {
	b, err := json.Marshal(requests)
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.Balance: encode request")
	}
	buf := c.bufs.Get()
	defer c.bufs.Put(buf)
	w := multipart.NewWriter(buf)
	w.WriteField("json", string(b))
	if files, ok := ctx.Value(contextKeyFiles).(map[string]file); ok {
		for fieldname, file := range files {
			f, err := w.CreateFormFile(fieldname, file.filename)
			if err != nil {
				return nil, errors.Wrap(err, "BankClient.Balance: create form file")
			}
			if _, err := io.Copy(f, file.r); err != nil {
				return nil, errors.Wrap(err, "BankClient.Balance: reading file")
			}
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			default:
			}
		}
	}
	if err := w.Close(); err != nil {
		return nil, errors.Wrap(err, "BankClient.Balance: write")
	}
	req, err := http.NewRequest(http.MethodPost, c.endpoint + "/remoto/Bank.Balance", buf)
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.Balance: new request")
	}
	req.Header.Set("Accept", "application/json; charset=utf-8")
	req.Header.Set("Content-Type", w.FormDataContentType())
	req = req.WithContext(ctx)
	resp, err := c.httpclient.Do(req)
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.Balance: do")
	}
	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, errors.Errorf("BankClient.Balance: remote service returned %s", resp.Status)
	}
	b, err = ioutil.ReadAll(resp.Body)
	resp.Body.Close()
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.Balance: read response body")
	}
	var resps []*Response
	if err := json.Unmarshal(b, &resps); err != nil {
		return nil, errors.Wrap(err, "BankClient.Balance: decode response body")
	}
	return resps, nil
}



func (c *BankClient) Pay(ctx context.Context, request *PaymentRequest) (*Response, error) {
	resp, err := c.PayMulti(ctx, []*PaymentRequest{request})
	if err != nil {
		return nil, err
	}
	if len(resp) == 0 {
		return nil, errors.New("BankClient.Pay: no response")
	}
	return resp[0], nil
}

func (c *BankClient) PayMulti(ctx context.Context, requests []*PaymentRequest) ([]*Response, error) {
	b, err := json.Marshal(requests)
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.Pay: encode request")
	}
	buf := c.bufs.Get()
	defer c.bufs.Put(buf)
	w := multipart.NewWriter(buf)
	w.WriteField("json", string(b))
	if files, ok := ctx.Value(contextKeyFiles).(map[string]file); ok {
		for fieldname, file := range files {
			f, err := w.CreateFormFile(fieldname, file.filename)
			if err != nil {
				return nil, errors.Wrap(err, "BankClient.Pay: create form file")
			}
			if _, err := io.Copy(f, file.r); err != nil {
				return nil, errors.Wrap(err, "BankClient.Pay: reading file")
			}
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			default:
			}
		}
	}
	if err := w.Close(); err != nil {
		return nil, errors.Wrap(err, "BankClient.Pay: write")
	}
	req, err := http.NewRequest(http.MethodPost, c.endpoint + "/remoto/Bank.Pay", buf)
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.Pay: new request")
	}
	req.Header.Set("Accept", "application/json; charset=utf-8")
	req.Header.Set("Content-Type", w.FormDataContentType())
	req = req.WithContext(ctx)
	resp, err := c.httpclient.Do(req)
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.Pay: do")
	}
	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, errors.Errorf("BankClient.Pay: remote service returned %s", resp.Status)
	}
	b, err = ioutil.ReadAll(resp.Body)
	resp.Body.Close()
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.Pay: read response body")
	}
	var resps []*Response
	if err := json.Unmarshal(b, &resps); err != nil {
		return nil, errors.Wrap(err, "BankClient.Pay: decode response body")
	}
	return resps, nil
}



func (c *BankClient) WithDraw(ctx context.Context, request *WithdrawlRequest) (*Response, error) {
	resp, err := c.WithDrawMulti(ctx, []*WithdrawlRequest{request})
	if err != nil {
		return nil, err
	}
	if len(resp) == 0 {
		return nil, errors.New("BankClient.WithDraw: no response")
	}
	return resp[0], nil
}

func (c *BankClient) WithDrawMulti(ctx context.Context, requests []*WithdrawlRequest) ([]*Response, error) {
	b, err := json.Marshal(requests)
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.WithDraw: encode request")
	}
	buf := c.bufs.Get()
	defer c.bufs.Put(buf)
	w := multipart.NewWriter(buf)
	w.WriteField("json", string(b))
	if files, ok := ctx.Value(contextKeyFiles).(map[string]file); ok {
		for fieldname, file := range files {
			f, err := w.CreateFormFile(fieldname, file.filename)
			if err != nil {
				return nil, errors.Wrap(err, "BankClient.WithDraw: create form file")
			}
			if _, err := io.Copy(f, file.r); err != nil {
				return nil, errors.Wrap(err, "BankClient.WithDraw: reading file")
			}
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			default:
			}
		}
	}
	if err := w.Close(); err != nil {
		return nil, errors.Wrap(err, "BankClient.WithDraw: write")
	}
	req, err := http.NewRequest(http.MethodPost, c.endpoint + "/remoto/Bank.WithDraw", buf)
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.WithDraw: new request")
	}
	req.Header.Set("Accept", "application/json; charset=utf-8")
	req.Header.Set("Content-Type", w.FormDataContentType())
	req = req.WithContext(ctx)
	resp, err := c.httpclient.Do(req)
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.WithDraw: do")
	}
	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, errors.Errorf("BankClient.WithDraw: remote service returned %s", resp.Status)
	}
	b, err = ioutil.ReadAll(resp.Body)
	resp.Body.Close()
	if err != nil {
		return nil, errors.Wrap(err, "BankClient.WithDraw: read response body")
	}
	var resps []*Response
	if err := json.Unmarshal(b, &resps); err != nil {
		return nil, errors.Wrap(err, "BankClient.WithDraw: decode response body")
	}
	return resps, nil
}





type BalaceRequest struct {
	
	AccountID string `json:"accountID"`
	Amount float64 `json:"amount"`
}










type PaymentRequest struct {
	
	AccountID string `json:"accountID"`
	Amount float64 `json:"amount"`
}










type Response struct {
	
	OK bool `json:"oK"`
	Message string `json:"message"`
	Amount float64 `json:"amount"`
	// Error is an error message if one occurred.
Error string `json:"error"`
}
















type WithdrawlRequest struct {
	
	AccountID string `json:"accountID"`
	Amount float64 `json:"amount"`
}











// contextKey is a local context key type.
// see https://medium.com/@matryer/context-keys-in-go-5312346a868d
type contextKey string

func (c contextKey) String() string {
	return "remoto context key: " + string(c)
}

// contextKeyFiles is the context key for the request files.
var contextKeyFiles = contextKey("files")

// file holds info about a file in the context, including
// the io.Reader where the contents will be read from.
type file struct {
	r io.Reader
	filename string
}

// this is here so we don't get a compiler complaints.
func init() {
	var _ = remototypes.File{}
	var _ = strconv.Itoa(0)
	var _ = ioutil.Discard
}
